# Kubernetes Deployment - Version 1
apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-application
  labels:
    app: web
    environment: production
spec:
  replicas: 2
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
        - name: web
          image: nginx:1.19
          ports:
            - containerPort: 80
          resources:
            limits:
              cpu: "500m"
              memory: "128Mi"
            requests:
              cpu: "250m"
              memory: "64Mi"
          env:
            - name: NODE_ENV
              value: "production"
        - name: sidecar
          image: busybox:1.32
          command: ["sh", "-c", "while true; do echo 'heartbeat'; sleep 60; done"]
